distro-base: fix validate_libraries

diff --git a/eks-distro-base/scripts/validate_libraries b/eks-distro-base/scripts/validate_libraries
--- a/eks-distro-base/scripts/validate_libraries
+++ b/eks-distro-base/scripts/validate_libraries
@@ -16,44 +16,24 @@
 set -e
 set -o pipefail
 
-NEWROOT_LD_LIBRARY_PATH="/newroot/lib64:/newroot/usr/lib64" 
-for sub_dir in $(find /newroot/usr/lib64 /newroot/lib64 -mindepth 1 -maxdepth 1 -type d); do
-    NEWROOT_LD_LIBRARY_PATH="$sub_dir:$NEWROOT_LD_LIBRARY_PATH"
-done
-
-# From: https://github.com/kubernetes-sigs/kind/blob/main/images/haproxy/stage-binary-and-deps.sh 
-binary_to_libraries() {
-    # see: https://man7.org/linux/man-pages/man1/ldd.1.html
-    LIBS=$(LD_LIBRARY_PATH=$NEWROOT_LD_LIBRARY_PATH ldd "${1}") 
-    echo $LIBS \
-    `# strip the leading '${name} => ' if any so only '/lib-foo.so (0xf00)' remains` \
-    | sed -E 's#.* => /#/#' \
-    `# we want only the path remaining, not the (0x${LOCATION})` \
-    | awk '{print $1}' \
-    `# linux-vdso.so.1 is a special virtual shared object from the kernel` \
-    `# see: http://man7.org/linux/man-pages/man7/vdso.7.html` \
-    | grep -v 'linux-vdso.so.1'
-
-}
+SCRIPT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
+source "${SCRIPT_ROOT}/eks-d-common"
 
 r_val=0
-for bin in $(find /newroot -executable -type f -not -name "*.so*"); do
-    if [ ! -f "${bin}" ] || [ ! -x "${bin}" ] || \
-        [ "$(binary_to_libraries $bin)" = "not" ] || [ "$(binary_to_libraries $bin)" = "statically" ]; then
+for bin in $(find $NEWROOT -executable -type f -not -name "*.so*"); do
+    if ! build::common::is_dynamic_binary $bin; then
         continue
     fi
-    echo "----- Checking $bin   -----"
+
+    echo "----- Checking $bin   -----"    
     while IFS= read -r c_dep; do
-        if [ "${c_dep}" != "not" ] && [ "${c_dep}" != "statically" ]; then
-            if [[ $c_dep = /newroot/* ]] && [ -f "${c_dep}" ]; then
+            if build::common::dep_exists "${c_dep}"; then
                 continue
             fi
-            if [ ! -f "/newroot${c_dep}" ] && [ ! -f "/newroot/usr${c_dep}" ]; then
-                echo "Missing DEP!!! ${c_dep}"
-                r_val=1
-            fi
-        fi
-    done < <(binary_to_libraries "${bin}")
+            echo "Missing DEP!!! ${c_dep}"
+            r_val=1
+           
+    done < <(build::common::binary_to_libraries "$bin")
     echo "----------------------------"
 done
 
